
title: How to visit IBS
description: General Travel Instruction to IBS, Daejeon, Korea
theme: just-the-docs
logo: "/assets/images/dimag.png"
url: https://travel.dimag.kr/

collections:
  destinations:
    output: false 
    sort_by: order
  origins:
    output: true
    sort_by: nav_order
    permalink: /:name/
  routes:
    output: false
    sort_by: order
defaults:
  - scope:
      path: ""
      type: origins
    values:
      layout: "origin"
      has_children: false
      has_toc: false
plugins:
  - jekyll-default-layout


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"
# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     # Reference the "tests" collection
#     origins:
#       # Give the collection a name
#       name: "Departing from"


nav_external_links:
  - title: IBS Discrete Mathematics Group
    url: https://dimag.ibs.re.kr/

liquid:
   error_mode: strict
   strict_filters: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_enabled: true
back_to_top: true
back_to_top_text: "Back to top"

ga_tracking: G-68RJR7KS5D
